// Product category generation for the Inventory Generation section.
//
// This module is intentionally pure and self-contained: given a list of
// generated SKUs, it assigns a deterministic `category` id to every SKU.
// Categories are **supporting data**, produced automatically like `demandScore`
// — there is NO user-facing slider for category count. They are consumed
// downstream by Inventory Placement's Category Clustering variable.
//
// --------------------------------------------------------------------------- //
// Independence from Product Affinity                                          //
// --------------------------------------------------------------------------- //
//
// `affinityGroup` (lib/taro/affinity.ts) and `category` (this module) describe
// two economically different signals:
//
//   • affinityGroup — co-purchase behaviour ("these tend to be bought
//                      together"), consumed by Order Generation.
//   • category      — product family membership ("these belong to the same
//                      family"), consumed by Inventory Placement.
//
// They are generated by SEPARATE engines with SEPARATE seeds and are never
// derived from one another. This module does not import `affinity.ts`, so the
// two concepts cannot accidentally couple at the data level.
//
// --------------------------------------------------------------------------- //
// Model: balanced latent product families                                     //
// --------------------------------------------------------------------------- //
//
// We assume the catalogue is partitioned into a small number of latent product
// families whose count scales with the catalogue size, `K = floor(sqrt(N))`
// clamped to [2, N] (or 0 for empty catalogues). Each family receives a
// comparably-sized share of the SKUs (balanced via largest-remainder
// apportionment, so every category is non-empty and no family dominates).
//
// Which specific SKUs fall into which family is decided by a seeded shuffle
// that spreads families across the numeric catalogue (SKU_001's family-mates
// are random SKUs, not adjacent ids), mirroring the realism choices made for
// affinity groups but using an independent seed stream.

/* -------------------------------------------------------------------------- */
/* Deterministic PRNG (mulberry32)                                            */
/* -------------------------------------------------------------------------- */

function mulberry32(seed: number): () => number {
  let a = seed >>> 0;
  return function next() {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/** Fisher–Yates shuffle driven by a seeded PRNG so results are reproducible. */
function seededShuffle<T>(values: T[], seed: number): T[] {
  const out = values.slice();
  const rng = mulberry32(seed);
  for (let i = out.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1));
    [out[i], out[j]] = [out[j], out[i]];
  }
  return out;
}

/* -------------------------------------------------------------------------- */
/* Category count                                                             */
/* -------------------------------------------------------------------------- */

/**
 * The number of latent product families a catalogue of `count` SKUs has.
 *
 * Scales as `floor(sqrt(count))` (bigger catalogues carry more families),
 * clamped to at least 2 once there is more than one SKU (so placement always
 * has a meaningful notion of "different categories" to cluster) and at most
 * `count`.
 *
 * This is the SAME math used by the affinity engine for `latentCategoryCount`,
 * but it is reimplemented here so that this module has zero coupling to
 * `affinity.ts`. The two are conceptually free to diverge in the future.
 */
export function latentFamilyCount(count: number): number {
  const n = Math.max(0, Math.floor(count));
  if (n <= 1) return n;
  return Math.min(Math.max(2, Math.floor(Math.sqrt(n))), n);
}

/* -------------------------------------------------------------------------- */
/* Balanced apportionment                                                      */
/* -------------------------------------------------------------------------- */

/**
 * Apportion `total` whole SKUs across `k` families as evenly as possible,
 * guaranteeing every family receives at least one SKU and the sizes sum to
 * exactly `total`. Uses the largest-remainder method with uniform weights, so
 * all families end up comparably-sized (differ by at most 1).
 */
function balancedApportion(total: number, k: number): number[] {
  if (k <= 0) return [];
  if (k === 1) return [total];
  const base = Math.floor(total / k);
  let leftover = total - base * k;
  const sizes = new Array<number>(k).fill(Math.max(1, base));
  // If base rounding under-allocated (e.g. total < k via the Math.max(1,...)
  // floor clamp), recompute leftover against the actual sum.
  let sum = sizes.reduce((a, b) => a + b, 0);
  leftover = total - sum;
  // Distribute leftover +1 (or absorb deficit -1) across families by index
  // order — deterministic and bounded by k.
  for (let i = 0; i < k && leftover !== 0; i++) {
    if (leftover > 0) {
      sizes[i]++;
      leftover--;
    } else {
      // Only trim families that have more than 1 so no family becomes empty.
      if (sizes[i] > 1) {
        sizes[i]--;
        leftover++;
      }
    }
  }
  return sizes;
}

/* -------------------------------------------------------------------------- */
/* Core generation                                                            */
/* -------------------------------------------------------------------------- */

export interface CategoryGenerationConfig {
  /** Number of SKUs to assign to a product family. */
  count: number;
  /**
   * Optional seed for reproducible family sizing and SKU-to-family assignment.
   * Defaults to a fixed seed distinct from the affinity engine's default so
   * the two assignments are decorrelated even when both use their defaults.
   */
  seed?: number;
}

/**
 * Generate a category id (1-based, contiguous) for every one of `count` SKUs.
 *
 * The returned array is index-aligned with the generated SKU list
 * (SKU_001 → index 0, …) so callers can zip it together without bookkeeping,
 * exactly like `generateDemandScores` and `generateAffinityGroups`.
 *
 * Properties of the returned ids:
 *   • length === count
 *   • every SKU gets exactly one positive integer family id (1-based)
 *   • family ids are contiguous: 1, 2, …, maxCategoryId (no empty families)
 *   • family sizes are balanced (differ by at most 1) and every family is
 *     non-empty
 *   • which SKU ids fall into which family is seeded/shuffled so families are
 *     spread across the catalogue rather than aligning with numeric SKU order
 */
export function generateCategoryIds(config: CategoryGenerationConfig): number[] {
  const n = Math.max(0, Math.floor(config.count));
  if (n === 0) return [];
  if (n === 1) return [1];

  const seed = config.seed ?? 0xc0ffee; // distinct from affinity's default 42.
  const k = latentFamilyCount(n);

  const sizes = balancedApportion(n, k);
  const groups = new Array<number>(n);
  const shuffledIndices = seededShuffle(
    Array.from({ length: n }, (_, i) => i),
    seed ^ 0x61c88647 // decorrelate from any sizing draws
  );
  let cursor = 0;
  for (let g = 0; g < sizes.length; g++) {
    const familyId = g + 1;
    for (let j = 0; j < sizes[g]; j++) {
      groups[shuffledIndices[cursor++]] = familyId;
    }
  }
  return groups;
}

/* -------------------------------------------------------------------------- */
/* Items enrichment helper (used by the layout-config overlay pipeline)       */
/* -------------------------------------------------------------------------- */

import type { Item } from './types';

/**
 * Enrich plain items with an independent `category` id from the product-family
 * engine. This is automatic supporting data — there is no user slider. Every
 * SKU is assigned to exactly one non-empty family.
 */
export function assignProductCategory(items: Item[], seed?: number): Item[] {
  if (items.length === 0) return items;
  const ids = generateCategoryIds({ count: items.length, seed });
  return items.map((item, i) => ({ ...item, category: ids[i] }));
}

/* -------------------------------------------------------------------------- */
/* Convenience summary (no UI consumer yet, kept for parity/tests)            */
/* -------------------------------------------------------------------------- */

export interface CategorySummary {
  /** Total number of distinct product families. */
  categoryCount: number;
  /** Size of the largest family. */
  largestFamilySize: number;
  /** Size of the smallest family. */
  smallestFamilySize: number;
  /** Mean number of SKUs per family (count / categoryCount). */
  meanFamilySize: number;
}

export function summarizeCategoryIds(ids: number[]): CategorySummary {
  const n = ids.length;
  if (n === 0) {
    return { categoryCount: 0, largestFamilySize: 0, smallestFamilySize: 0, meanFamilySize: 0 };
  }
  const counts = new Map<number, number>();
  for (const c of ids) counts.set(c, (counts.get(c) ?? 0) + 1);
  let largest = 0;
  let smallest = Number.POSITIVE_INFINITY;
  for (const size of counts.values()) {
    if (size > largest) largest = size;
    if (size < smallest) smallest = size;
  }
  return {
    categoryCount: counts.size,
    largestFamilySize: largest,
    smallestFamilySize: smallest,
    meanFamilySize: n / counts.size,
  };
}