// Core data types for Taro warehouse simulation

// Branded types for grid coordinates to prevent mixing coordinates
export type GridX = number & { readonly __brand: 'GridX' };
export type GridY = number & { readonly __brand: 'GridY' };

// Helper functions to create branded types
export const gridX = (value: number): GridX => value as GridX;
export const gridY = (value: number): GridY => value as GridY;

export type CellType = 'empty' | 'shelf' | 'worker-start';

/**
 * An Item is a discrete unit of inventory. Each Item has a unique id.
 *
 * `demandScore` is an optional, positive number that expresses how much
 * customer demand a SKU attracts relative to other SKUs. It is produced by
 * the Demand Distribution inventory-generation variable. A mean of ~1 is
 * maintained regardless of distribution, so the slider only redistributes
 * demand across SKUs rather than scaling the total pool.
 *
 * `affinityGroup` is an optional, positive integer that identifies the
 * Product Affinity group a SKU belongs to. It is produced by the Product
 * Affinity inventory-generation variable. SKUs that share the same affinity
 * group are considered related and are more likely to be ordered together.
 * Every SKU is assigned to exactly one affinity group (singletons get their
 * own unique group id), so the value is always defined once generated.
 *
 * `category` is an optional, positive integer that identifies the product
 * family a SKU belongs to. It is produced automatically during Inventory
 * Generation as supporting data (like `demandScore`), and is intentionally
 * INDEPENDENT of `affinityGroup`: affinity describes co-purchase behaviour
 * (consumed by Order Generation) while category describes product family
 * membership (consumed by Inventory Placement's Category Clustering). The
 * two are generated by separate engines with separate seeds and must never
 * be derived from one another. Every SKU is assigned to exactly one category
 * once generated.
 *
 * `storageFootprint` is an optional, positive integer that expresses HOW
 * MANY storage locations a SKU requires. It is produced by the Storage
 * Footprint inventory-generation variable and is an INTRINSIC property of
 * the inventory (like demand, affinity, and category) — it does NOT perform
 * any placement itself. Inventory Placement consumes it to decide how many
 * (contiguous) bins each SKU occupies; Slotting Bias and Category Clustering
 * continue to decide WHERE those bins sit. A value of 1 (the default when
 * absent) means the SKU occupies exactly one bin, preserving the legacy
 * one-SKU-one-bin behaviour.
 *
 * `totalQuantity` is the total inventory quantity for this SKU across ALL
 * its storage locations. Storage Footprint only controls HOW MANY bins the
 * quantity is split across; it does NOT multiply it. When a SKU occupies
 * N bins, `totalQuantity` is divided evenly among them, with any remainder
 * assigned to the primary (nearest-to-dispatch) bin. The invariant is:
 *
 *     Σ bin.quantity for a SKU == totalQuantity
 *
 * A value of 50 (the default when absent) preserves backward compatibility
 * for the legacy one-SKU-one-bin model where every bin carried 50 units.
 */
export interface Item {
  id: string;
  demandScore?: number;
  affinityGroup?: number;
  /** Product family id, independent of affinityGroup. Consumed by placement. */
  category?: number;
  /** How many storage locations this SKU requires. Consumed by placement. */
  storageFootprint?: number;
  /**
   * Total inventory quantity across all bins for this SKU.
   * When absent, placement defaults to 50 (backward compatible).
   */
  totalQuantity?: number;
}

/**
 * A StorageLocation is a single bin: one slot on one shelf at one z-level.
 * Each bin carries exactly one SKU and its stock quantity.
 *
 * A SKU may now span MULTIPLE storage locations (its `storageFootprint`).
 * When it does, exactly one of its bins is marked `primary: true` — the bin
 * that downstream code (order resolution, simulation, UI labels) treats as
 * the SKU's canonical pick location. Secondary bins hold additional capacity
 * but are never added to a pick list directly. The primary is chosen by
 * Inventory Placement as the nearest-to-dispatch bin of the SKU's contiguous
 * group. Legacy/manually-built warehouses where `primary` is absent are
 * treated as the old one-SKU-one-bin model.
 *
 * Invariant: every `id` is unique across all StorageLocations. When the
 *            `primary` field is present for a SKU, exactly one of that
 *            SKU's bins carries `primary: true`.
 */
export interface StorageLocation {
  id: string;
  locationId: string;
  x: number;
  y: number;
  z: number;
  sku: string;
  quantity: number;
  /**
   * True on the canonical pick bin for a multi-location SKU. Exactly one bin
   * per SKU is primary (set by Inventory Placement). Absent on legacy bins.
   */
  primary?: boolean;
  /**
   * Demand weight from the Demand Distribution variable (0=Uniform, 100=Pareto).
   * Used by order generation to bias toward high-demand SKUs.
   * Absent on legacy/demo/CSV/manual bins (order generation defaults to 1).
   */
  demandScore?: number;
  /**
   * Affinity group id from the Product Affinity variable (0=Independent,
   * 100=Highly Related). Used by order generation to bias SKU co-purchase
   * toward items in the same affinity group.
   * Absent on legacy/demo/CSV/manual bins (no co-purchase bias applied).
   */
  affinityGroup?: number;
}

export interface Cell {
  x: number;
  y: number;
  type: CellType;
  locations: StorageLocation[];
}

/**
 * A WarehouseLocation is a physical shelf (the shelf itself, not a single bin).
 * It groups the bins that sit on that shelf so callers can answer shelf-level
 * questions (which aisle/rack/column) without scanning every StorageLocation.
 */
export interface WarehouseLocation {
  id: string;
  x: number;
  y: number;
  type: 'shelf';
  binIds: string[];
}

export interface OrderItem {
  skuId: string;
  quantity?: number;
}

export interface Order {
  id: string;
  items: OrderItem[];
  assignedWorkerId: number | null; // null = Auto
}

export interface WorkerPosition {
  x: number;
  y: number;
}

export interface Warehouse {
  width: number;
  height: number;
  grid: Cell[][];
  shelves: { x: number; y: number }[];
  workerStart: WorkerPosition | null;
  locations: WarehouseLocation[];
}

/**
 * Workspace model — pairs a warehouse layout with its DB metadata (name, position).
 * This is the canonical representation of a warehouse node on the React Flow canvas.
 */
export interface WorkspaceWarehouse {
  id: string;
  name: string;
  position: { x: number; y: number } | null;
  warehouse: Warehouse;
}

export interface WarehouseProfile {
  scale: number; // meters per grid cell
  workerSpeed: number; // meters per minute
  pickTimePerItem: number; // seconds per pick
}

export interface Neighbor {
  x: number;
  y: number;
  edgeCost: number;
}

export type NeighborGraph = Map<string, Neighbor[]>;

export interface LaborProfile {
  costPerHour: number;
}

export interface SimulationProfiles {
  warehouseProfile?: Partial<WarehouseProfile>;
  laborProfile?: Partial<LaborProfile>;
  /** When true, unresolvable order lines are skipped instead of aborting the run. */
  allowPartial?: boolean;
  /** Number of orders to group into one batch (used by Batch Picking strategy). Default: 5. */
  batchSize?: number;
}

export type StrategyType = 'single' | 'batch' | 'zone';

export interface WorkerRoute {
  workerId: number;
  route: { x: number; y: number }[];
  picks: { locationKey: string; x: number; y: number; z: number; sku: string; pickCount?: number }[];
  tasks: PickTask[];
  color: string;
  zone: string;
  assignedPickCount: number;
  progress: number;
}

export interface StrategyResult {
  strategy: StrategyType;
  strategyName: string;
  distance: number;
  totalDistance: number;
  criticalPathDistance: number;
  estimatedTime: number;
  efficiency: number;
  workerUtilization: number;
  costPerOrder: number;
  route: { x: number; y: number }[];
  color: string;
  workerRoutes: WorkerRoute[];
  /** Number of orders that had at least one successful pick. */
  ordersCompleted: number;
  /** Number of orders with zero successful picks (all items missing or unreachable). */
  ordersSkipped: number;
  /** Number of pick targets that A* could not reach. */
  unreachablePicks: number;
}

export interface SimulationResults {
  strategies: StrategyResult[];
  heatmap: number[][];
  bestStrategy: StrategyType;
  isPartial: boolean;
  unresolvableItems: string[];
  missingItemsCount: number;
  invalidLocationCount: number;
  validationContext?: SimulationValidationContext;
}

export interface OrderValidationResult {
  orderId: string;
  missingSkuIds: string[];
}

export interface SimulationValidationContext {
  totalItems: number;
  missingItems: number;
  affectedOrders: number;
  missingItemsByOrder: OrderValidationResult[];
}

export type ToolType = 'hand' | 'shelf' | 'worker' | 'erase';

export type ZVisualizationMode = 'all' | 'level1' | 'level2' | 'level3' | 'level4';

export interface PickTask {
  workerId: number;
  step: number;
  zone: string;
  location: string;
  sku: string;
}

export interface SimulationBlockState {
  /** Set when simulation cannot run; drives right-panel blocked UI. */
  simulationState?: 'NO_VALID_ITEMS' | 'UNREACHABLE_LOCATIONS';
  title: string;
  description: string;
}
